### ISSUE TITLE
Problems about loading pretrained model.

### ISSUE THREAD

**Issue by zhuangxinkai** [YuWang24/MultiTune#2]
Thanks for your code. 
But when I run your code in my device, in which the version of pytorch is 1.5.0, and the version of python is 3.6, a error occurs:

```Traceback (most recent call last):
  File "main.py", line 390, in <module>
    net = get_model("resnet26", num_class, dataset = "imagenet12")
  File "main.py", line 295, in get_model
    rnet = load_weights_to_flatresnet(source, rnet, num_class, dataset)
  File "main.py", line 233, in load_weights_to_flatresnet
    checkpoint = torch.load(source, map_location=lambda storage, loc: storage, pickle_module=pickle)
  File "/public/home/G20060068_11/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/public/home/G20060068_11/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```

Have you ever met this problem? How can I fix this error?

**Comment by masyitahabu** [comment]
Thank for your code I also get same error as zhuangxinkai

**Comment by YuWang24** [comment]
That's a problem related to the pickle encoding. You can try to change the encoding in these lines: https://github.com/YuWang24/MultiTune/blob/50f6c59d3d82f3e5804c09969500498b7d581177/main.py#L230-L231 Hope this can help.

**Comment by masyitahabu** [comment]
Thank you very much it help me a lot
